import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-2 w-screen h-screen overflow-hidden">
          <div className="bg-[#F1EFEF]">asdsa</div>
          <div className="flex flex-col gap-3 justify-center items-center">{children}</div>
        </div>
      </body>
    </html>
  );
}
