import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-2 w-screen h-screen overflow-hidden">
          <div className="bg-[#F1EFEF]"></div>
          <div className="flex flex-col justify-center items-center">{children}</div>
        </div>
      </body>
    </html>
  );
}
